---
title: "Exploration of odonates dataset"
author: "Dragon CESAB"
format: dashboard
---

# General Overview
```{r load}
library(plotly)
library(terra)
library(mapview)
library(tmap)
library(heatmaply)
tab <- readRDS(here::here("data", "derived-data", "occ_all_df.rds"))
rastat <- readRDS(here::here("data", "derived-data", "stat_10000.rds"))
ra84 <- project(rastat, crs("EPSG:3857"))
# set the function to calculate the number of unique elements
nodup <- function(x) {return(sum(!duplicated(x)))}

# interactive mode for tmap
suppressMessages(tmap_mode("view"))
```



## Row {height=40%}

### Column {.tabset}

```{r obsyear}
#| title: obs
# number of observation per database
nobs_dbyear <- aggregate(tab$observationID, list(tab$dbID, tab$Year), nodup)
plot_ly(nobs_dbyear, x = ~Group.2, y = ~x, color = ~Group.1) %>% 
    layout(xaxis = list(title = 'Year'),
           yaxis = list(title = 'Number of observations'), 
           barmode = 'stack')
```

```{r gridyear}
#| title: cell
# number of cells per year per country
ngrid_countyear <- aggregate(tab$grid10kmID, list(tab$Country, tab$Year), nodup)
plot_ly(ngrid_countyear, x = ~Group.2, y = ~x, color = ~Group.1) %>% 
    layout(xaxis = list(title = 'Year'),
           yaxis = list(title = 'Number of grid cells'), 
           barmode = 'stack')
```

```{r taxayear}
#| title: taxa
nspe_famyear <- aggregate(tab$species, list(tab$family, tab$Year), nodup)
plot_ly(nspe_famyear, x = ~Group.2, y = ~x, color = ~Group.1) %>% 
        layout(xaxis = list(title = 'Year'),
           yaxis = list(title = 'Number of grid cells'), 
           barmode = 'stack')
```

### Column {.tabset}


```{r}
#| title: taxa per db
# number of species per database per year
nspe_db_year <- tapply(tab$species, list(tab$dbID,tab$Year), nodup)
plot_ly(x=colnames(nspe_db_year), y=rownames(nspe_db_year), z = nspe_db_year, type = "heatmap") %>%
    layout(margin = list(l=120))
```


```{r}
#| title: cell per species
# number of observations per database per year
# nobs_db_year <- table(tab$dbID, tab$Year)
# nobs_db_year[nobs_db_year==0] <- NA
ngrid_sp_year <- tapply(tab$grid10kmID, list(tab$species,tab$Year), nodup)
plot_ly(x=colnames(ngrid_sp_year), y=rownames(ngrid_sp_year), z = ngrid_sp_year, type = "heatmap") %>%
    layout(margin = list(l=120))
```




## Row {height=50% .tabset}


```{r spemap}
#| title: spe
tm_shape(rastat) +
       tm_raster("nspe", interpolate=FALSE, breaks = (0:8)*10) +
       tm_view(basemap.server = "OpenStreetMap")
```


```{r obsmap}
#| title: obs
rastat$logobs <- log(rastat$nobs)
tm_shape(rastat) +
       tm_raster("nobs", interpolate=FALSE, 
       breaks = c(0,1,5,10,50,100, 500,1000, 5000,15000)) +
       tm_view(basemap.server = "OpenStreetMap")

```


```{r yrmap}
#| title: year
tm_shape(rastat) +
       tm_raster("nyr", interpolate=FALSE) +
       tm_view(basemap.server = "OpenStreetMap")
```


```{r yr5map}
#| title: year5
tm_shape(rastat) +
       tm_raster("nyr5", interpolate=FALSE) +
       tm_view(basemap.server = "OpenStreetMap")
```



